# Site settings
title: Nicolás Hock-Isaza
email: nhocki@gmail.com
description: Thoughts about programming, development & other stuff.
author: Nicolás Hock-Isaza
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.nhocki.com"
twitter_username: nhocki
github_username:  nhocki

timezone: 'America/Bogota'
relative_permalinks: true
permalink: /:year/:month/:day/:title/

gems:
  - jemoji

# Build settings
markdown: redcarpet

redcarpet:
  extensions:
    - autolink
    - strikethrough
    - tables
    - no_intra_emphasis
    - with_toc_data
